[workspace]
resolver = "2"

members = [
    "authorization",
    "hello_world",
    "increment",
    "custom_types",
    "cross_contract_calls",
    "liquidity_pool",
    "liquidity_pool_router",
    "single_offer",
    "single_offer_xfer_from",
    "single_offer_router",
]

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[patch.crates-io]
soroban-sdk = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "bba4039" }
soroban-sdk-macros = { git = "https://github.com/stellar/rs-soroban-sdk", rev = "bba4039" }
soroban-env-common = { git = "https://github.com/stellar/rs-soroban-env", rev = "7395b81" }
soroban-env-guest = { git = "https://github.com/stellar/rs-soroban-env", rev = "7395b81" }
soroban-env-host = { git = "https://github.com/stellar/rs-soroban-env", rev = "7395b81" }
soroban-env-macros = { git = "https://github.com/stellar/rs-soroban-env", rev = "7395b81" }
soroban-native-sdk-macros = { git = "https://github.com/stellar/rs-soroban-env", rev = "7395b81" }
stellar-xdr = { git = "https://github.com/stellar/rs-stellar-xdr", rev = "dbfb606" }
soroban-token-contract = { git = "https://github.com/stellar/soroban-token-contract", rev = "4a525ea" }
