name: Stellar expert release contracts workflow
on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Unique name for the release'
        required: true
        type: string
jobs:
  release-soroswap-token:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'soroswap token contract release'
      relative_path: './contracts/token'
      package: 'soroban-token-contract'
      make_target: './Makefile'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
    needs: []
  release-soroswap-pair:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'soroswap pair contract release'
      relative_path: './contracts/pair'
      package: 'soroswap-pair'
      make_target: './Makefile'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
    needs: [release-soroswap-token]
  release-soroswap-factory:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'soroswap factory contract release'
      relative_path: './contracts/factory'
      package: 'soroswap-factory'
      make_target: './Makefile'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
    needs: [release-soroswap-token, release-soroswap-pair]
  release-soroswap-library:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'soroswap library contract release'
      relative_path: './contracts/library'
      package: 'soroswap-library'
      make_target: './Makefile'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
    needs:  [release-soroswap-token, release-soroswap-pair, release-soroswap-factory]
  release-soroswap-router:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'soroswap router contract release'
      relative_path: './contracts/router'
      package: 'soroswap-router'
      make_target: './Makefile'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
    needs:  [release-soroswap-token, release-soroswap-pair, release-soroswap-factory]
  
    
