name: Build contracts and release  # name it whatever you like
on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Unique release name'
        required: true
        type: string
jobs:
  release-soroswap-factory:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}                      # use git tag as unique release name
      release_description: 'Soroswap factory contract release'  # some boring placeholder text to attach
      relative_path: '["contracts/factory"]'                    # relative path to your really awesome contract
      package: 'Soroswap-factory'                               # package name to build
      make_target: 'contracts/factory/Makefile'                 # make target to invoke
    secrets:  # the authentication token will be automatically created by GitHub
      release_token: ${{ secrets.GITHUB_TOKEN }}                # don't modify this line
  release-soroswap-library:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'Soroswap library contract release'
      relative_path: '["contracts/library"]'
      package: 'Soroswap-library'
      make_target: 'contracts/library/Makefile'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
  release-soroswap-pair:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'Soroswap pair contract release'
      relative_path: '["contracts/pair"]'
      package: 'Soroswap-pair'
      make_target: 'contracts/pair/Makefile'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
  release-soroswap-router:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'Soroswap router contract release'
      relative_path: '["contracts/router"]'
      package: 'Soroswap-router'
      make_target: 'contracts/router/Makefile'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
  release-soroswap-token:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'Soroswap token contract release'
      relative_path: '["contracts/token"]'
      package: 'Soroswap-token'
      make_target: 'contracts/token/Makefile'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
