name: Build ../contracts and release  # name it whatever you like
on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Unique release name'
        required: true
        type: string
jobs:
  release-soroswap-token:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'soroswap token contract release'
      relative_path: '["../../contracts/token"]'
      package: 'token'
      make_target: '["../../contracts/token/Makefile"]'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
    needs: []
  release-soroswap-pair:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'soroswap pair contract release'
      relative_path: '["../../contracts/pair"]'
      package: 'pairs'
      make_target: '["../../contracts/pair/Makefile"]'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
    needs: [release-soroswap-token]
  release-soroswap-factory:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}                      # use git tag as unique release name
      release_description: 'soroswap factory contract release'  # some boring placeholder text to attach
      relative_path: '["../../contracts/factory"]'                    # relative path to your really awesome contract
      package: 'factory'                               # package name to build
      make_target: '["../../contracts/factory/Makefile"]'                 # make target to invoke
    secrets:  # the authentication token will be automatically created by GitHub
      release_token: ${{ secrets.GITHUB_TOKEN }}                # don't modify this line
    needs: [release-soroswap-token, release-soroswap-pair]
  release-soroswap-library:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'soroswap library contract release'
      relative_path: '["../../contracts/library"]'
      package: 'library'
      make_target: '["../../contracts/library/Makefile"]'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
    needs:  [release-soroswap-token, release-soroswap-pair, release-soroswap-factory]
  release-soroswap-router:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: ${{ github.ref_name }}
      release_description: 'soroswap router contract release'
      relative_path: '["../../contracts/router"]'
      package: 'router'
      make_target: '["../../contracts/router/Makefile"]'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
    needs:  [release-soroswap-token, release-soroswap-pair, release-soroswap-factory]
  
    
